# Instala dependencias necesarias antes de la build
[phases.setup]
apt_pkgs = ["postgresql-client"] # 🔑 Esto instala pg_dump y pg_restore

# Fase de instalación de dependencias Node.js
[phases.install]
cmds = ["npm install --legacy-peer-deps"]

# Fase de build
[phases.build]
cmds = ["npm run build"]

# Fase de ejecución
[phases.start]
cmd = "npm run start:prod"

# Configuración de caché para despliegues más rápidos
[caches]
paths = ["/root/.npm"]

# Variables opcionales (puedes sobrescribir en Coolify)
[variables]
NODE_ENV = "production"
PORT = "4000"
